//
// Generated file, do not edit! Created by nedtool 5.6 from create_message_event.msg.
//

#ifndef __CREATE_MESSAGE_EVENT_M_H
#define __CREATE_MESSAGE_EVENT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>create_message_event.msg:3</tt> by nedtool.
 * <pre>
 * message CreateMessageEvent
 * {
 * }
 * </pre>
 */
class CreateMessageEvent : public ::omnetpp::cMessage
{
  protected:

  private:
    void copy(const CreateMessageEvent& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CreateMessageEvent&);

  public:
    CreateMessageEvent(const char *name=nullptr, short kind=0);
    CreateMessageEvent(const CreateMessageEvent& other);
    virtual ~CreateMessageEvent();
    CreateMessageEvent& operator=(const CreateMessageEvent& other);
    virtual CreateMessageEvent *dup() const override {return new CreateMessageEvent(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CreateMessageEvent& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CreateMessageEvent& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CREATE_MESSAGE_EVENT_M_H

