//
// Generated file, do not edit! Created by nedtool 5.6 from health_measurement_event.msg.
//

#ifndef __HEALTH_MEASUREMENT_EVENT_M_H
#define __HEALTH_MEASUREMENT_EVENT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>health_measurement_event.msg:3</tt> by nedtool.
 * <pre>
 * message HealthMeasurementEvent
 * {
 * }
 * </pre>
 */
class HealthMeasurementEvent : public ::omnetpp::cMessage
{
  protected:

  private:
    void copy(const HealthMeasurementEvent& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HealthMeasurementEvent&);

  public:
    HealthMeasurementEvent(const char *name=nullptr, short kind=0);
    HealthMeasurementEvent(const HealthMeasurementEvent& other);
    virtual ~HealthMeasurementEvent();
    HealthMeasurementEvent& operator=(const HealthMeasurementEvent& other);
    virtual HealthMeasurementEvent *dup() const override {return new HealthMeasurementEvent(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HealthMeasurementEvent& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HealthMeasurementEvent& obj) {obj.parsimUnpack(b);}


#endif // ifndef __HEALTH_MEASUREMENT_EVENT_M_H

