//
// Generated file, do not edit! Created by nedtool 5.6 from pacing_event.msg.
//

#ifndef __PACING_EVENT_M_H
#define __PACING_EVENT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>pacing_event.msg:2</tt> by nedtool.
 * <pre>
 * message PacingEvent
 * {
 *     int neighbor = 0;
 * }
 * </pre>
 */
class PacingEvent : public ::omnetpp::cMessage
{
  protected:
    int neighbor;

  private:
    void copy(const PacingEvent& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PacingEvent&);

  public:
    PacingEvent(const char *name=nullptr, short kind=0);
    PacingEvent(const PacingEvent& other);
    virtual ~PacingEvent();
    PacingEvent& operator=(const PacingEvent& other);
    virtual PacingEvent *dup() const override {return new PacingEvent(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getNeighbor() const;
    virtual void setNeighbor(int neighbor);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PacingEvent& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PacingEvent& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PACING_EVENT_M_H

