//
// Generated file, do not edit! Created by nedtool 5.6 from request_message_event.msg.
//

#ifndef __REQUEST_MESSAGE_EVENT_M_H
#define __REQUEST_MESSAGE_EVENT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>request_message_event.msg:2</tt> by nedtool.
 * <pre>
 * message RequestMessageEvent
 * {
 *     string requestId;
 * }
 * </pre>
 */
class RequestMessageEvent : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::opp_string requestId;

  private:
    void copy(const RequestMessageEvent& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RequestMessageEvent&);

  public:
    RequestMessageEvent(const char *name=nullptr, short kind=0);
    RequestMessageEvent(const RequestMessageEvent& other);
    virtual ~RequestMessageEvent();
    RequestMessageEvent& operator=(const RequestMessageEvent& other);
    virtual RequestMessageEvent *dup() const override {return new RequestMessageEvent(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getRequestId() const;
    virtual void setRequestId(const char * requestId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RequestMessageEvent& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RequestMessageEvent& obj) {obj.parsimUnpack(b);}


#endif // ifndef __REQUEST_MESSAGE_EVENT_M_H

