//
// Generated file, do not edit! Created by nedtool 5.6 from request_message.msg.
//

#ifndef __REQUEST_MESSAGE_M_H
#define __REQUEST_MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>request_message.msg:2</tt> by nedtool.
 * <pre>
 * message RequestMessage
 * {
 *     string requestId;
 * }
 * </pre>
 */
class RequestMessage : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::opp_string requestId;

  private:
    void copy(const RequestMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RequestMessage&);

  public:
    RequestMessage(const char *name=nullptr, short kind=0);
    RequestMessage(const RequestMessage& other);
    virtual ~RequestMessage();
    RequestMessage& operator=(const RequestMessage& other);
    virtual RequestMessage *dup() const override {return new RequestMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getRequestId() const;
    virtual void setRequestId(const char * requestId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RequestMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RequestMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __REQUEST_MESSAGE_M_H

